### ISSUE TITLE
Will it work for LaBSE 2 version?

### ISSUE THREAD

**Issue by takiholadi** [setu4993/convert-labse-tf-pt#1]
https://tfhub.dev/google/LaBSE/2

**Comment by setu4993** [comment]
@takiholadi : Thanks for flagging! Haven't tried it, but I'm assuming yes. I can try it over the weekend and check in a few days.

**Comment by setu4993** [comment]
@takiholadi : Updated the model to [v2 on the HF Hub](https://huggingface.co/setu4993/LaBSE/tree/v2). FWIW, it is an identical model ([see this test](https://github.com/setu4993/convert-labse-tf-pt/blob/ec3a019159a54ed6493181a64486c2808c01f216/tests/test_conversion.py#L31)) with slightly different inputs.
