### ISSUE TITLE
Question about Fine tuning

### ISSUE THREAD

**Issue by Z4HRA-S** [setu4993/convert-labse-tf-pt#32]
This model should take two sentences in two different languages; should we pass a tuple of texts to the model?

**Comment by setu4993** [comment]
@Z4HRA-S : Unfortunately, I'm not familiar with how to fine-tune this model. My experience with it has been limited to consuming the model to generate embeddings and to convert it from TensorFlow to PyTorch.

I'd recommend reaching out to the authors of the [original paper](https://arxiv.org/abs/2007.01852) over email to discuss with them.
